### ISSUE TITLE
We need a world menu

### ISSUE THREAD

**Issue by bergel** [OBJECTSEMANTICS/GraphQL#10]
We need a world menu:
- To start and stop the server. 
- Define the schema
- see some example of query
- open a webpage on the GitHub repository (Roassal does something like this)
- report an issue

**Comment by bergel** [comment]
This menu should be also available in VisualWorks 7.4, if possible

**Comment by akevalion** [comment]
<img width="333" alt="captura de pantalla 2018-11-21 a la s 19 04 53" src="https://user-images.githubusercontent.com/10532890/48870663-680d3580-edc0-11e8-8382-b6144ddfe76d.png">

There is a new world menu
